### ISSUE TITLE
conda recipe

### ISSUE THREAD

**Issue by pkestene** [byrnereese/mkdocs-minify-plugin#10]
Hello,

if I'm not mistaken there is no conda recipe for mkdocs-minify-plugin
as I would be interested in having one, I wrote a draft here:
https://github.com/pkestene/staged-recipes/tree/recipe/mkdocs-minify-plugin/recipes/mkdocs-minify-plugin

let me know what you think, perhaps would prefer to do it yourself and submit to conda-forge ?

**Comment by wilhelmer** [comment]
Sorry for the late reply. I have no experience with Conda, so if you want to submit a receipe, feel free to do so.
