### ISSUE TITLE
[critical] jsmin dependency is not compatible with latest setuptools

### ISSUE THREAD

**Issue by NicolasMassart** [byrnereese/mkdocs-minify-plugin#15]
jsmin dependency is not compatible with latest setuptools making mkdocs-minify-plugin fail the mkdocs build on readthedocs.org for instance, but also on any environment using setuptools latest version.
See https://github.com/tikitu/jsmin/issues/33

**Comment by wilhelmer** [comment]
There's a PR at jsmin (https://github.com/tikitu/jsmin/pull/34) that will fix this. Let's hope it will get merged. Otherwise, I'll pin setuptools as suggested.

**Comment by hoechenberger** [comment]
A new version of jsmin, 3.0.0, has been released and should resolve this issue.

**Comment by wilhelmer** [comment]
Thanks for the info. I've updated the dependencies and released v0.4.1.

@byrnereese Could you please upload the new version to PyPI or give me the rights to do so? Thank you!

**Comment by byrnereese** [comment]
@wilhelmer New version released.
