### ISSUE TITLE
Error: The "minify-plugin" plugin is not installed

### ISSUE THREAD

**Issue by coliff** [byrnereese/mkdocs-minify-plugin#2]
Thanks for the work creating this plugin! I'm having trouble getting it to run though. I ran `pip install mkdocs-minify-plugin` and it successfully downloaded the plugins code to `C:\Python\Lib\site-packages\mkdocs_minify_plugin`. I added this to my `config.yml`
```
plugins:
    - search
    - minify-plugin
```

However, when I run `mkdocs build` I get the error:
```
ERROR   -  Config value: 'plugins'. Error: The "mkdocs_minify_plugin" plugin is not installed
```

Any ideas? I'm on Windows 10 64-bit and have MkDocs v1.0.4 and Python 3.7 and using the MkDocs-Material theme.

**Comment by coliff** [comment]
I got it working with this config:

```
plugins:
    - search
    - minify
```

I'll open a PR for that change. :-)

**Comment by coliff** [comment]
Hi @byrnereese - can you merge that PR please?

**Comment by byrnereese** [comment]
Merged. Sorry for the delay.
